export const AUTH_ERROR_CODES = {
  UNAUTHORIZED_ERROR: '401',
  EXPIRED_TOKEN_ERROR: '401-1',
  INVALID_TOKEN_ERROR: '401-2',
  EXPIRED_REFRESH_TOKEN_ERROR: '401-3',
  NOT_VALID_ACCESS_TOKEN_ERROR: '401-4',
} as const;
